# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json (or yarn.lock) from your project into the working directory
COPY package*.json ./
# If you are using yarn, uncomment the next line and comment out the npm install line
# COPY yarn.lock ./

# Install dependencies
RUN npm install
# If you are using yarn, use the following command instead
# RUN yarn install

# Copy the rest of your application's code
COPY . .

# Build the application for production
RUN npm run build
# If you are using yarn, use the following command instead
# RUN yarn build

# Install a lightweight server to serve the static files
RUN npm install -g serve
# If you are using yarn, use the following command instead
# RUN yarn global add serve

# Command to run the server
CMD ["serve", "-s", "dist", "-l", "5000"]

# Expose the port the app runs on
EXPOSE 5000